---

#==============================================================================================
# Available tags:
#
#   snapshot
#   tenants
#   vrf
#   bd
#   gw
#   ap
#   epg
#   domain
#   static_binding
#
#==============================================================================================

- name:                            Create Application Profile
  hosts:                           apic_amslab
  connection:                      local
  gather_facts:                    no

#==============================================================================================
# Create or delete. Comment out as required.
#==============================================================================================
  vars:
    desired_state:                 present
#    desired_state:                absent

#    desired_status:               create,modified
#    desired_status:               delete"

#==============================================================================================
# APIC access information.
#==============================================================================================
    apic_info:                     &apic_info
      host:                        "{{ apic_ip }}"
      username:                    "{{ apic_username }}"
      password:                    "{{ apic_password }}"
      validate_certs:              no

    rest_info:                     &rest_info
      use_proxy:                   no
      path:                        /api/mo/.json
      method:                      post

#==============================================================================================
# Tenants.
#==============================================================================================
    tenants:
      - { tenant: "CiscoLive", descr: "Created by Ansible" }

#==============================================================================================
# VRFs.
#==============================================================================================
    vrf:
      - { tenant: "common", vrf: "vrf-01", descr: "Created by Ansible"}

#==============================================================================================
# Bridge Domains.
#==============================================================================================
    bd:
      - { tenant: "common", vrf: "vrf-01", descr: "Created by Ansible", bd: "192.168.2.x_24", state: "present" }

#==============================================================================================
# Gateways.
#==============================================================================================
    gw:
      - { tenant: "common", vrf: "vrf-01", descr: "Created by Ansible", bd: "192.168.2.x_24", gw: "192.168.2.1", mask: "24", state: "present" }

#==============================================================================================
# Application Profiles.
#==============================================================================================
    ap:
#      - { tenant: "Legacy", app_profile: "192.168.2.x_24", descr: "Created by Ansible" }
      - { tenant: "CiscoLive", app_profile: "WordPress", descr: "Created by Ansible" }

#==============================================================================================
# EPGs.
#==============================================================================================
    epg:
#      - { tenant: "legacy", app_profile: "192.168.2.x_24", bd: "192.168.2.x_24", epg: "vlan-2", descr: "Created by Ansible" }
      - { tenant: "CiscoLive", app_profile: "WordPress", bd: "192.168.2.x_24", epg: "Frontend", descr: "Created by Ansible" }
      - { tenant: "CiscoLive", app_profile: "WordPress", bd: "192.168.2.x_24", epg: "Backend", descr: "Created by Ansible" }

#==============================================================================================
# Domains.
#==============================================================================================
    domain:
#      - { tenant: "legacy", app_profile: "192.168.2.x_24", epg: "vlan-2", domain_name: "HX-ACI", domain_type: "vmm", vm_provider: "vmware" }
      - { tenant: "CiscoLive", app_profile: "WordPress", epg: "Frontend", domain_name: "HX-ACI", domain_type: "vmm", vm_provider: "vmware" }
      - { tenant: "CiscoLive", app_profile: "WordPress", epg: "Backend", domain_name: "HX-ACI", domain_type: "vmm", vm_provider: "vmware" }

#==============================================================================================
# Bindings.
#==============================================================================================
    static_binding:
#      - { tenant: "legacy", app_profile: "192.168.2.x_24", epg: "vlan-2", leafs: "101-102", path: "vpc_to_legacy_n7k", vlan: "2" }


#==============================================================================================
# Variables complete. Task execution from here.
#==============================================================================================

  tasks:
    - name:                        Create an APIC Snapshot
      aci_config_snapshot:
        <<:                        *apic_info
        state:                     present
        export_policy:             config_backup
        max_count:                 10
        description:               Snapshot Created by Ansible
      tags:
        - snapshot
        - demo5


    - name:                        Create Tenant
      aci_tenant:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        description:               "{{ item.descr }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ tenants }}"
      tags:                        tenants


    - name:                        Create VRF
      aci_vrf:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        vrf:                       "{{ item.vrf }}"
        description:               "{{ item.descr }}"
        policy_control_preference: enforced
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ vrf }}"
      tags:                        vrf


    - name:                        Create Bridge Domain
      aci_bd:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        vrf:                       "{{ item.vrf }}"
        bd:                        "{{ item.bd }}"
        description:               "{{ item.descr }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ bd }}"
      tags:                        bd


    - name:                        Create Bridge Domain Subnet
      aci_bd_subnet:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        bd:                        "{{ item.bd }}"
        gateway:                   "{{ item.gw }}"
        mask:                      "{{ item.mask }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ gw }}"
      tags:                        gw


    - name:                        Create Application Profile
      aci_ap:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        ap:                        "{{ item.app_profile }}"
        description:               "{{ item.descr }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ ap }}"
      tags:
        - ap
        - demo5


    - name:                        Create EPG
      aci_epg:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        ap:                        "{{ item.app_profile }}"
        bd:                        "{{ item.bd }}"
        epg:                       "{{ item.epg }}"
        description:               "{{ item.descr }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ epg }}"
      tags:
        - epg
        - demo5


    - name:                        Add domain to an EPG
      aci_epg_to_domain:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        ap:                        "{{ item.app_profile }}"
        epg:                       "{{ item.epg }}"
        domain:                    "{{ item.domain_name }}"
        domain_type:               "{{ item.domain_type }}"
        vm_provider:               "{{ item.vm_provider }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ domain }}"
      tags:
        - domain
        - demo5


    - name:                        Deploy Static Path binding for given EPG
      aci_static_binding_to_epg:
        <<:                        *apic_info
        tenant:                    "{{ item.tenant }}"
        ap:                        "{{ item.app_profile }}"
        epg:                       "{{ item.epg }}"
        encap_id:                  "{{ item.vlan }}"
        deploy_immediacy:          immediate
        interface_mode:            trunk
        interface_type:            vpc
        pod_id:                    1
        leafs:                     "{{ item.leafs }}"
        interface:                 "{{ item.path }}"
        state:                     "{{ desired_state }}"
      with_items:
        - "{{ static_binding }}"
      tags:                        static_binding
